library identifier: 'pipeline-utils@main',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/JaimeSalas/pipeline-utils.git'])

pipeline {
    agent any 
    stages {
        stage('Audit Tools') {
            steps {
                auditTools2 message: 'This is demo 2'
            }
        }
    }
}